[package]
name = "alphacalc"
version = "0.1.0"
authors = ["TheLie0 <wf7za0XoHyYXVEkOeNu8>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
natural_constants = "0.1.0"
flume = "0.7.1"
image = "0.23.5"
